version: '3.8'
services:
  galileo-server:
    build: .
    ports:
      - "8888:8888"
      - "8888:8888/udp"
      - "8086:8086"
    volumes:
      - ./var/lib:/Last_of_Us_System/var/lib
      - ./var/logs:/Last_of_Us_System/var/logs
      - ./backup:/Last_of_Us_System/backup
    command: build/bin/server
  galileo-client:
    build: .
    volumes:
      - ./var/logs:/Last_of_Us_System/var/logs
    command: build/bin/client galileo-server
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"
  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"

  volumes:
  galileo-db:
  galileo-logs:
  galileo-backup: