#include "unity.h"
#include <sqlite3.h>

extern "C" {

/**
 * @brief Unity hook called before each test.
 */
void setUp(void) {
}

/**
 * @brief Unity hook called after each test.
 */
void tearDown(void) {
}

/* Prototypes for C tests */

void test_process_input_returns_send_for_normal_message();
void test_process_input_returns_quit_for_end_command();
void test_process_input_returns_continue_for_empty_input();
void test_build_json_for_simple_command();
void test_build_json_for_command_with_args();
void test_build_json_fails_on_missing_arguments();
void test_input_arguments_success();
void test_parse_arguments_fails_on_insufficient_args();
void test_parse_arguments_fails_on_invalid_port();
void test_build_json_get_stock_success();
void test_build_json_get_stock_fails_on_missing_arguments();
void test_build_json_login_success();
void test_build_json_login_missing_field();
void test_initialize_udp_peer_address_copies_data();
void test_build_json_update_stock_fails_invalid_quantity();
void test_print_simple_response_formats_success();
void test_print_get_inventory_response_formats_success();
void test_print_get_inventory_response_formats_error();
void test_print_get_history_response_formats_success();
void test_print_get_history_response_formats_empty();
void test_print_get_stock_response_formats_success();
void test_print_get_stock_response_formats_error();
void test_print_get_history_response_error();
void test_login_success();
void test_login_missing_client_id();
void test_login_error_response();
void test_execute_client_action_error();
void test_execute_client_action_continue();
void test_execute_client_action_quit_error();
void test_execute_client_action_syntax_error();
void test_execute_client_action_send_error();
void test_logger_init_success();
void test_logger_init_fail();
void test_logger_log_writes_to_file();
void test_level_to_string();
void test_parse_arguments_invalid_env_tcp_port();
void test_parse_arguments_env_tcp_port();
void test_parse_arguments_arguments_override_env_port();
void test_parse_arguments_invalid_env_udp_port();
void test_parse_arguments_ports_from_one_arg();
void test_parse_arguments_invalid_udp_args();
void test_setup_and_connect_fails_with_invalid_port_string();
void test_setup_and_connect_fails_with_invalid_host();
void test_setup_and_connect_fails_with_invalid_udp_port_string();
void test_ipc_init();
void test_ipc_priority_check();
void test_ipc_priority_check_invalid_json();
void test_ipc_send_message_long_message_fails();
void test_ipc_send_message_not_initialized_fails();
void test_ipc_send_message_success();
void test_ipc_exit();
void test_start_communication_fails_uninitialized_socket();
void test_execute_client_action_success();
void test_execute_client_action_server_closed();
void test_execute_client_action_recv_error();
void test_start_communication_user_quit();
void test_start_communication_send_error();
void test_socket_validation_success_tcp();
void test_socket_validation_success_udp();
void test_socket_validation_error();
void test_launch_dashboard_fails_without_clientID();
void test_build_json_register_user_new_client_successfully();
void test_build_json_register_user_missing_fields();
void test_build_json_unlock_client_success();
void test_build_json_unlock_client_missing_fields();
} // extern "C"

void testProcessCommandStatusAsJSON();
void testProcessCommandEndAsJSON();
void testProcessCommandUnknownAsJSON();
void testServerConstructorFailsOnPrivilegedPort();
void testProcessCommandUpdateStockAsJSON();
void testProcessCommandSrvrInMaintenance();
void testProcessCommandNoCommand();
void testProcessCommandNoPayloadForUpload();
void testProcessCommandUpdateStockInvalidQuantityType();
void testProcessCommandNoQuantityForUpload();
void testProcessCommandNoCategoryForUpload();
void testProcessCommandNoItemForUpload();
void testUpdateStockAddsNewItem();
void testUpdateStockModifiesExistingItem();
void testGetInventorySummaryForUnknownClientReturnsEmpty();
void testGetInventorySummaryReturnsCorrectMapFromDataBase();
void testUpdateStockNegativeQuantity();
void testSessionStartsUnauthenticated();
void testSessionAuthenticatesWithValidLogin();
void testSessionAuthenticatesWithInvalidLogin();
void testSessionRejectsOtherCommandsWhenUnauthenticated();
void testProcessMessageHandlesMalformedJson();
void testProcessCommandgetInventory();
void testProcessCommandgGetEmptyInventory();
void testProcessMessageHandlesInvalidLoginRequest();
void testSaveStockUpdate();
void testSaveStockUpdateModifiesExistingRow();
void testInitializeSchemaCreatesTables();
void testSaveStockUpdateThrowsOnConstraintViolation();
void testInitializeSchemaThrowsOnInvalidConnection();
void testGetStockFromDataBase();
void testGetStockReturnsEmptyForNonExistentItem();
void testProcessCommandGetStockSuccessfully();
void testProcessCommandGetStockNoItemFound();
void testProcessCommandInvalidPayloadForGetStock();
void testGetStockThrowsIfSchemaNotInitialized();
void testGetStockRetrievesFromDatabaseOnCacheMiss();
void testGetFullInventorySuccess();
void testGetFullInventoryNoClientFound();
void testGetFullInventoryThrowsIfTableNotInitialized();
void testCreateUserSuccess();
void testUserNotInTable();
void testGetHostnamePasswordhash();
void testNoHostnameforGetHostnamePasswordhash();
void testUpdateLoginAttempts();
void testUpdateLoginAttemptsUpToFour();
void testUpdateLoginAttemptsResets();
void testAuthenticatorSucceedsWithValidCredentials();
void testAuthenticatorFailsWithInvalidPassword();
void testAuthenticatorFailsWithUnknownUser();
void testAuthenticatorFailsWithFailedAttempts();
void testAuthenticatorResetsFailedAttempts();
void testProcessMessageAuthenticatedCommand();
void testProcessMessageCatchExceptionFromAuthenticatedCommand();
void testAuthenticatorPassAfterBlockedTime();
void testCreateUserThrows();
void testUserExistsThrowsWithNoTable();
void testgetUserLoginThrows();
void testCreateUserFailsOnDuplicate();
void testgetInventorySummaryFromDataBase();
void testUserDoesntExists();
void testSaveLogEntrySuccess();
void testSaveLogEntryThrowsWithInvalidUser();
void testSystemLog();
void testComponentLogWithClientID();
void testGetStockEmptyForNoUser();
void testLogFailsGracefullyWithInvalidClientId();
void testLogLevel();
void testCreateLoggableRequestMasksPassword();
void testProcessMessageUserReachLimitFailedAttemps();
void testProcessCommandUpdateStockNegativeQuantity();
void testgetInventoryHistoryTransactionSuccessfull();
void testgetInventoryHistoryTransactionEmptyForNoLogs();
void testgetInventoryHistoryTransactionEmptyForNoUser();
void testGetFullInventoryIsEmpty();
void testCommnadGetHistoryNoLogsEmptyData();
void testCommnadGetHistory();
void testUpdateStockInvalidItem();
void testUpdateStockInvalidCategory();
void testIsClientLocked();
void testSetClientLockStatus();
void testIsClientLockedHandlesCacheMiss();
void testLockAndUnlockClient();
void testProcessAlertLocksClientOnValidAlert();
void testProcessAlertHandlesMalformedJsonGracefully();
void testProcessMessageUserLockedAlertTrigger();
void testValidatorFailsOnExcessiveArgs();
void testValidatorFailsOnNonNumericPort();
void testValidatorSucceedsWithNoArgs();
void testValidatorSucceedsWithCorrectArgs();
void testValidatorrInvalidPortNumber();
void testValidatorZeroNumberPort();
void testValidatesFalseFileNotFound();
void testConfigLoadsPortFromYaml();
void testConfigPrioritizesCliArgumentOverYaml();
void testConfigLoadsdbPathFromYaml();
void testConfigSecretPhraseFromYaml();
void testUnlockClientWithCorrectSecretPhrase();
void testUnlockClientWrongClient();
void testUnlockClientWrongPhrase();
void testUnlockClientWrongPayload();
void testUnlockClientNotAdminUser();
void testIsClientLockedThrowsNoTable();
void testSetClientLockStatusThrowsNoTable();
void testGetInventoryHistoryThrowsNoTable();
void testgetInventorySummaryFromCacheHit();
void testRegisterAndUnregisterSession();
void testsetUdpAddress();
void testgetActiveUdpAddresses();
void testSessionManagerGetClientSession();
void testLockNonExistentClient();
void testGetClientIpIpv4();
void testGetClientIpIpv6();
void testGetClientIpInvalid();
void testClientSessionHandlesSQlExceptionOnLogin();
void testConfigPrioritizesEnvVariableOverYaml();
void testConfigPrioritizesCliArgumentsTcpAndUdp();
void testConfigFailsOnInvalidEnvPort();
void testConfigFailsOnInvalidPortInYaml();
void testConfigCliArgumentHasPriorityOverEnv();
void testConfigFailsOnMissingDbPathInYaml();
void testConfigFailsOnMissingSecretPhraseInYaml();
void testIpcHandlerReadError();
void testConfigLoadsFromDefaultWhenNoArgs();
void testOpenLogFileSuccess();
void testOpenLogFileFailure();
void testLoggerWritesToFile();
void testLoggerCloseLogFile();
void testLoggerLogRotation();
void testCompressFileGzipFailsOnInvalidPath();
void testShouldRotateTrue();
void testTrafficReporterCounters();
void testUpdateStockFailsWithHubUser();
void testEventQueuePushLimitErasesOld();
void testEventQueuePopEmpty();
void testThreadpoolExecutesTask();
void testClientSessionEventQueueHandleNoUDPDirection();
void testWelcomeMessageFails();
void testHasPendingMessages();
void testTrySendPendingMessageFails();
void testRegisterNewClientSuccessfully();
void testRegisterNewClientMissingFields();
void testRegisterNewClientNotAdminUser();

/**
 * @brief Runs all the tests.
 *
 * Call all the tests for each c and cpp files in one runner(this file)
 *
 * @return 0 on success, non-zero on failure.
 */
int main() {

    UNITY_BEGIN();
    RUN_TEST(testProcessCommandStatusAsJSON);
    RUN_TEST(testProcessCommandEndAsJSON);
    RUN_TEST(testProcessCommandUnknownAsJSON);
    RUN_TEST(testServerConstructorFailsOnPrivilegedPort);
    RUN_TEST(test_process_input_returns_send_for_normal_message);
    RUN_TEST(test_process_input_returns_quit_for_end_command);
    RUN_TEST(test_process_input_returns_continue_for_empty_input);
    RUN_TEST(test_build_json_for_simple_command);
    RUN_TEST(test_build_json_for_command_with_args);
    RUN_TEST(test_build_json_fails_on_missing_arguments);
    RUN_TEST(testProcessCommandUpdateStockAsJSON);
    RUN_TEST(testProcessCommandSrvrInMaintenance);
    RUN_TEST(testProcessCommandNoCommand);
    RUN_TEST(testProcessCommandNoPayloadForUpload);
    RUN_TEST(testProcessCommandUpdateStockInvalidQuantityType);
    RUN_TEST(testProcessCommandNoQuantityForUpload);
    RUN_TEST(testProcessCommandNoCategoryForUpload);
    RUN_TEST(testProcessCommandNoItemForUpload);
    RUN_TEST(testUpdateStockAddsNewItem);
    RUN_TEST(testUpdateStockModifiesExistingItem);
    RUN_TEST(testGetInventorySummaryForUnknownClientReturnsEmpty);
    RUN_TEST(testUpdateStockNegativeQuantity);
    RUN_TEST(testAuthenticatorSucceedsWithValidCredentials);
    RUN_TEST(testSessionStartsUnauthenticated);
    RUN_TEST(testSessionAuthenticatesWithValidLogin);
    RUN_TEST(testSessionAuthenticatesWithInvalidLogin);
    RUN_TEST(testSessionRejectsOtherCommandsWhenUnauthenticated);
    RUN_TEST(testProcessMessageHandlesMalformedJson);
    RUN_TEST(testProcessCommandgetInventory);
    RUN_TEST(testProcessCommandgGetEmptyInventory);
    RUN_TEST(testProcessMessageHandlesInvalidLoginRequest);
    RUN_TEST(testSaveStockUpdate);
    RUN_TEST(testSaveStockUpdateModifiesExistingRow);
    RUN_TEST(testInitializeSchemaCreatesTables);
    RUN_TEST(testSaveStockUpdateThrowsOnConstraintViolation);
    RUN_TEST(testInitializeSchemaThrowsOnInvalidConnection);
    RUN_TEST(testGetStockFromDataBase);
    RUN_TEST(testGetStockEmptyForNoUser);
    RUN_TEST(testGetStockReturnsEmptyForNonExistentItem);
    RUN_TEST(testProcessCommandGetStockSuccessfully);
    RUN_TEST(testProcessCommandGetStockNoItemFound);
    RUN_TEST(testProcessCommandInvalidPayloadForGetStock);
    RUN_TEST(testGetStockThrowsIfSchemaNotInitialized);
    RUN_TEST(testGetStockRetrievesFromDatabaseOnCacheMiss);
    RUN_TEST(testGetFullInventorySuccess);
    RUN_TEST(testGetFullInventoryNoClientFound);
    RUN_TEST(testGetFullInventoryThrowsIfTableNotInitialized);
    RUN_TEST(testCreateUserSuccess);
    RUN_TEST(testUserNotInTable);
    RUN_TEST(testGetHostnamePasswordhash);
    RUN_TEST(testNoHostnameforGetHostnamePasswordhash);
    RUN_TEST(testUpdateLoginAttempts);
    RUN_TEST(testUpdateLoginAttemptsUpToFour);
    RUN_TEST(testUpdateLoginAttemptsResets);
    RUN_TEST(testAuthenticatorFailsWithInvalidPassword);
    RUN_TEST(testAuthenticatorFailsWithUnknownUser);
    RUN_TEST(testAuthenticatorFailsWithFailedAttempts);
    RUN_TEST(testAuthenticatorResetsFailedAttempts);
    RUN_TEST(testProcessMessageAuthenticatedCommand);
    RUN_TEST(testProcessMessageCatchExceptionFromAuthenticatedCommand);
    RUN_TEST(testAuthenticatorPassAfterBlockedTime);
    RUN_TEST(testCreateUserThrows);
    RUN_TEST(testUserExistsThrowsWithNoTable);
    RUN_TEST(testgetUserLoginThrows);
    RUN_TEST(testCreateUserFailsOnDuplicate);
    RUN_TEST(testUserDoesntExists);
    RUN_TEST(testSaveLogEntrySuccess);
    RUN_TEST(testSaveLogEntryThrowsWithInvalidUser);
    RUN_TEST(testSystemLog);
    RUN_TEST(testComponentLogWithClientID);
    RUN_TEST(testLogFailsGracefullyWithInvalidClientId);
    RUN_TEST(testLogLevel);
    RUN_TEST(testCreateLoggableRequestMasksPassword);
    RUN_TEST(testProcessMessageUserReachLimitFailedAttemps);
    RUN_TEST(testProcessCommandUpdateStockNegativeQuantity);
    RUN_TEST(testgetInventoryHistoryTransactionSuccessfull);
    RUN_TEST(testgetInventoryHistoryTransactionEmptyForNoLogs);
    RUN_TEST(testgetInventoryHistoryTransactionEmptyForNoUser);
    RUN_TEST(testGetFullInventoryIsEmpty);
    RUN_TEST(testCommnadGetHistoryNoLogsEmptyData);
    RUN_TEST(testCommnadGetHistory);
    RUN_TEST(test_input_arguments_success);
    RUN_TEST(test_parse_arguments_fails_on_insufficient_args);
    RUN_TEST(test_parse_arguments_fails_on_invalid_port);
    RUN_TEST(test_build_json_get_stock_success);
    RUN_TEST(test_build_json_get_stock_fails_on_missing_arguments);
    RUN_TEST(test_build_json_login_success);
    RUN_TEST(test_build_json_login_missing_field);
    RUN_TEST(test_build_json_update_stock_fails_invalid_quantity);
    RUN_TEST(test_initialize_udp_peer_address_copies_data);
    RUN_TEST(testUpdateStockInvalidItem);
    RUN_TEST(testUpdateStockInvalidCategory);
    RUN_TEST(test_print_simple_response_formats_success);
    RUN_TEST(test_print_get_inventory_response_formats_success);
    RUN_TEST(test_print_get_inventory_response_formats_error);
    RUN_TEST(test_print_get_history_response_formats_success);
    RUN_TEST(test_print_get_history_response_formats_empty);
    RUN_TEST(test_print_get_stock_response_formats_success);
    RUN_TEST(test_print_get_stock_response_formats_error);
    RUN_TEST(testIsClientLocked);
    RUN_TEST(testSetClientLockStatus);
    RUN_TEST(testIsClientLockedHandlesCacheMiss);
    RUN_TEST(testLockAndUnlockClient);
    RUN_TEST(testProcessAlertLocksClientOnValidAlert);
    RUN_TEST(testProcessAlertHandlesMalformedJsonGracefully);
    RUN_TEST(testProcessMessageUserLockedAlertTrigger);
    RUN_TEST(testValidatorFailsOnExcessiveArgs);
    RUN_TEST(testValidatorFailsOnNonNumericPort);
    RUN_TEST(testValidatorSucceedsWithNoArgs);
    RUN_TEST(testValidatorSucceedsWithCorrectArgs);
    RUN_TEST(testValidatorrInvalidPortNumber);
    RUN_TEST(testValidatorZeroNumberPort);
    RUN_TEST(testValidatesFalseFileNotFound);
    RUN_TEST(test_print_get_history_response_error);
    RUN_TEST(testConfigLoadsPortFromYaml);
    RUN_TEST(testConfigPrioritizesCliArgumentOverYaml);
    RUN_TEST(testConfigLoadsdbPathFromYaml);
    RUN_TEST(testConfigSecretPhraseFromYaml);
    RUN_TEST(testUnlockClientWithCorrectSecretPhrase);
    RUN_TEST(testUnlockClientWrongClient);
    RUN_TEST(testUnlockClientWrongPhrase);
    RUN_TEST(testUnlockClientWrongPayload);
    RUN_TEST(testUnlockClientNotAdminUser);
    RUN_TEST(testIsClientLockedThrowsNoTable);
    RUN_TEST(testSetClientLockStatusThrowsNoTable);
    RUN_TEST(testGetInventoryHistoryThrowsNoTable);
    RUN_TEST(testgetInventorySummaryFromCacheHit);
    RUN_TEST(testGetInventorySummaryReturnsCorrectMapFromDataBase);
    RUN_TEST(testRegisterAndUnregisterSession);
    RUN_TEST(testsetUdpAddress);
    RUN_TEST(testgetActiveUdpAddresses);
    RUN_TEST(testSessionManagerGetClientSession);
    RUN_TEST(testLockNonExistentClient);
    RUN_TEST(testGetClientIpIpv4);
    RUN_TEST(testGetClientIpIpv6);
    RUN_TEST(testGetClientIpInvalid);
    RUN_TEST(testClientSessionHandlesSQlExceptionOnLogin);
    RUN_TEST(test_login_success);
    RUN_TEST(test_login_missing_client_id);
    RUN_TEST(test_login_error_response);
    RUN_TEST(test_execute_client_action_error);
    RUN_TEST(test_execute_client_action_continue);
    RUN_TEST(test_execute_client_action_quit_error);
    RUN_TEST(test_execute_client_action_syntax_error);
    RUN_TEST(test_execute_client_action_send_error);
    RUN_TEST(test_logger_init_success);
    RUN_TEST(test_logger_init_fail);
    RUN_TEST(test_logger_log_writes_to_file);
    RUN_TEST(test_level_to_string);
    RUN_TEST(test_parse_arguments_invalid_env_tcp_port);
    RUN_TEST(test_parse_arguments_env_tcp_port);
    RUN_TEST(test_parse_arguments_arguments_override_env_port);
    RUN_TEST(test_parse_arguments_invalid_env_udp_port);
    RUN_TEST(testConfigPrioritizesEnvVariableOverYaml);
    RUN_TEST(testConfigPrioritizesCliArgumentsTcpAndUdp);
    RUN_TEST(testConfigFailsOnInvalidEnvPort);
    RUN_TEST(testConfigFailsOnInvalidPortInYaml);
    RUN_TEST(testConfigCliArgumentHasPriorityOverEnv);
    RUN_TEST(testConfigFailsOnMissingDbPathInYaml);
    RUN_TEST(testConfigFailsOnMissingSecretPhraseInYaml);
    RUN_TEST(test_parse_arguments_ports_from_one_arg);
    RUN_TEST(test_parse_arguments_invalid_udp_args);
    RUN_TEST(test_setup_and_connect_fails_with_invalid_port_string);
    RUN_TEST(test_setup_and_connect_fails_with_invalid_host);
    RUN_TEST(test_setup_and_connect_fails_with_invalid_udp_port_string);
    RUN_TEST(test_ipc_init);
    RUN_TEST(test_ipc_priority_check);
    RUN_TEST(test_ipc_priority_check_invalid_json);
    RUN_TEST(test_ipc_send_message_long_message_fails);
    RUN_TEST(test_ipc_send_message_not_initialized_fails);
    RUN_TEST(test_ipc_send_message_success);
    RUN_TEST(test_ipc_exit);
    RUN_TEST(test_start_communication_fails_uninitialized_socket);
    RUN_TEST(test_execute_client_action_success);
    RUN_TEST(test_execute_client_action_server_closed);
    RUN_TEST(test_execute_client_action_recv_error);
    RUN_TEST(test_start_communication_user_quit);
    RUN_TEST(test_start_communication_send_error);
    RUN_TEST(test_socket_validation_success_tcp);
    RUN_TEST(test_socket_validation_success_udp);
    RUN_TEST(test_socket_validation_error);
    RUN_TEST(testIpcHandlerReadError);
    RUN_TEST(test_launch_dashboard_fails_without_clientID);
    RUN_TEST(testConfigLoadsFromDefaultWhenNoArgs);
    RUN_TEST(testOpenLogFileSuccess);
    RUN_TEST(testOpenLogFileFailure);
    RUN_TEST(testLoggerWritesToFile);
    RUN_TEST(testLoggerCloseLogFile);
    RUN_TEST(testLoggerLogRotation);
    RUN_TEST(testCompressFileGzipFailsOnInvalidPath);
    RUN_TEST(testShouldRotateTrue);
    RUN_TEST(testTrafficReporterCounters);
    RUN_TEST(testUpdateStockFailsWithHubUser);
    RUN_TEST(testEventQueuePushLimitErasesOld);
    RUN_TEST(testEventQueuePopEmpty);
    RUN_TEST(testThreadpoolExecutesTask);
    RUN_TEST(testClientSessionEventQueueHandleNoUDPDirection);
    RUN_TEST(testWelcomeMessageFails);
    RUN_TEST(testHasPendingMessages);
    RUN_TEST(testTrySendPendingMessageFails);
    RUN_TEST(testRegisterNewClientSuccessfully);
    RUN_TEST(testRegisterNewClientMissingFields);
    RUN_TEST(testRegisterNewClientNotAdminUser);
    RUN_TEST(test_build_json_register_user_new_client_successfully);
    RUN_TEST(test_build_json_register_user_missing_fields);
    RUN_TEST(test_build_json_unlock_client_success);
    RUN_TEST(test_build_json_unlock_client_missing_fields);
    return UNITY_END();
}